# Generated by Django 5.1.2 on 2025-01-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeteoblueData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('modelrun_utc', models.DateTimeField()),
                ('utc_timeoffset', models.FloatField()),
                ('generation_time_ms', models.FloatField()),
                ('time', models.JSONField()),
                ('temperature_instant', models.JSONField()),
                ('temperature_max', models.JSONField()),
                ('temperature_min', models.JSONField()),
                ('windspeed_mean', models.JSONField()),
                ('sealevelpressure_mean', models.JSONField()),
                ('precipitation', models.JSONField()),
                ('precipitation_hours', models.JSONField()),
                ('predictability', models.JSONField()),
                ('pictocode', models.JSONField()),
                ('winddirection', models.JSONField()),
                ('uvindex', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='measurement',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
