# Generated by Django 5.1.2 on 2025-02-02 13:32

import django.contrib.postgres.fields
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_meteobluedata_forecastdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastdata',
            name='pictocode',
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='pictocode',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
        migrations.RemoveField(
            model_name='forecastdata',
            name='precipitation',
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='precipitation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
        migrations.RemoveField(
            model_name='forecastdata',
            name='precipitation_hours',
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='precipitation_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
        migrations.RemoveField(
            model_name='forecastdata',
            name='predictability',
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='predictability',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
        migrations.RemoveField(
            model_name='forecastdata',
            name='sealevelpressure_mean',
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='sealevelpressure_mean',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
        migrations.RemoveField(
            model_name='forecastdata',
            name='temperature_instant',
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='temperature_instant',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
        migrations.RemoveField(
            model_name='forecastdata',
            name='temperature_max',
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='temperature_max',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
        migrations.RemoveField(
            model_name='forecastdata',
            name='temperature_min',
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='temperature_min',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
        migrations.RemoveField(
            model_name='forecastdata',
            name='time',
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.RemoveField(
            model_name='forecastdata',
            name='uvindex',
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='uvindex',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
        migrations.RemoveField(
            model_name='forecastdata',
            name='winddirection',
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='winddirection',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
        migrations.RemoveField(
            model_name='forecastdata',
            name='windspeed_mean',
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='windspeed_mean',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
    ]
