# Generated by Django 5.1.2 on 2025-02-02 13:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_forecastdata_pictocode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastdata',
            name='temperature_mean',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
    ]
