# Generated by Django 5.1.2 on 2025-02-13 07:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_forecastdata_relativehumidity_mean_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastdata',
            name='felttemperature_mean',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
    ]
