# Generated by Django 5.1.2 on 2025-02-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_station_measurement_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='city_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
