# Generated by Django 5.1.2 on 2025-02-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_station_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastdata',
            name='city_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
