# Generated by Django 5.1.2 on 2025-03-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_measurementstat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementstat',
            name='rain',
        ),
        migrations.RemoveField(
            model_name='measurementstat',
            name='wind_direction',
        ),
        migrations.RemoveField(
            model_name='measurementstat',
            name='wind_speed',
        ),
        migrations.AddField(
            model_name='measurementstat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
