# Generated by Django 5.1.2 on 2025-03-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_measurementstat_rain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementstat',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
