# Generated by Django 5.1.2 on 2025-04-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_measurementstat_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
