# Generated by Django 5.1.2 on 2025-04-07 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_measurement_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='rain',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='wind_direction',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='wind_speed',
        ),
    ]
