# Generated by Django 5.1.2 on 2025-04-07 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_measurement_pressure_remove_measurement_rain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementstat',
            name='pressure',
        ),
    ]
